// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasajeYa.Infrastructure.Data;

#nullable disable

namespace PasajeYa.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PasajeYaDbContext))]
    partial class PasajeYaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasajeYa.Domain.Entities.Boleto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumeroAsiento")
                        .HasColumnType("int");

                    b.Property<int>("ViajeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViajeId");

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("PasajeYa.Domain.Entities.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 32,
                            Placa = "BDS275",
                            TipoServicio = "Economico"
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 48,
                            Placa = "KFC192",
                            TipoServicio = "Economico"
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 32,
                            Placa = "PIL483",
                            TipoServicio = "Ejecutivo"
                        },
                        new
                        {
                            Id = 4,
                            Capacidad = 28,
                            Placa = "JFK581",
                            TipoServicio = "Ejecutivo"
                        },
                        new
                        {
                            Id = 5,
                            Capacidad = 16,
                            Placa = "MGM397",
                            TipoServicio = "Vip"
                        },
                        new
                        {
                            Id = 6,
                            Capacidad = 14,
                            Placa = "FIT814",
                            TipoServicio = "Vip"
                        });
                });

            modelBuilder.Entity("PasajeYa.Domain.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Lima"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Arequipa"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Trujillo"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Tacna"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Piura"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Cajamarca"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Cusco"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Huancayo"
                        });
                });

            modelBuilder.Entity("PasajeYa.Domain.Entities.Ruta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<int>("OrigenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigenId", "DestinoId")
                        .IsUnique();

                    b.ToTable("Rutas", t =>
                        {
                            t.HasCheckConstraint("CK_Rutas_OrigenDistintoDestino", "[OrigenId]<>[DestinoId]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinoId = 2,
                            OrigenId = 1
                        },
                        new
                        {
                            Id = 2,
                            DestinoId = 3,
                            OrigenId = 1
                        },
                        new
                        {
                            Id = 3,
                            DestinoId = 4,
                            OrigenId = 1
                        },
                        new
                        {
                            Id = 4,
                            DestinoId = 5,
                            OrigenId = 1
                        },
                        new
                        {
                            Id = 5,
                            DestinoId = 6,
                            OrigenId = 1
                        },
                        new
                        {
                            Id = 6,
                            DestinoId = 1,
                            OrigenId = 2
                        },
                        new
                        {
                            Id = 7,
                            DestinoId = 3,
                            OrigenId = 2
                        },
                        new
                        {
                            Id = 8,
                            DestinoId = 4,
                            OrigenId = 2
                        },
                        new
                        {
                            Id = 9,
                            DestinoId = 5,
                            OrigenId = 2
                        },
                        new
                        {
                            Id = 10,
                            DestinoId = 1,
                            OrigenId = 3
                        },
                        new
                        {
                            Id = 11,
                            DestinoId = 7,
                            OrigenId = 3
                        },
                        new
                        {
                            Id = 12,
                            DestinoId = 8,
                            OrigenId = 3
                        },
                        new
                        {
                            Id = 13,
                            DestinoId = 4,
                            OrigenId = 3
                        },
                        new
                        {
                            Id = 14,
                            DestinoId = 1,
                            OrigenId = 5
                        },
                        new
                        {
                            Id = 15,
                            DestinoId = 3,
                            OrigenId = 6
                        });
                });

            modelBuilder.Entity("PasajeYa.Domain.Entities.Viaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Llegada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RutaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Salida")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("RutaId");

                    b.ToTable("Viajes");
                });

            modelBuilder.Entity("PasajeYa.Domain.Entities.Boleto", b =>
                {
                    b.HasOne("PasajeYa.Domain.Entities.Viaje", "Viaje")
                        .WithMany()
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("PasajeYa.Domain.Entities.Ruta", b =>
                {
                    b.HasOne("PasajeYa.Domain.Entities.Ciudad", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PasajeYa.Domain.Entities.Ciudad", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("PasajeYa.Domain.Entities.Viaje", b =>
                {
                    b.HasOne("PasajeYa.Domain.Entities.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PasajeYa.Domain.Entities.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Ruta");
                });
#pragma warning restore 612, 618
        }
    }
}
